### ISSUE TITLE
Is it possible to upload some version for .NET Framework 4.5 xxx?

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Sewer56/Reloaded.Imgui.Hook#3]
Hello, Is it possible to compile under the .Net Framework 4.5 or higher?

**Comment by Sewer56** [comment]
Probably. 
I'd need to add netstandard2.0 TFM to DearImGuiSharp dependency. 

Aside from that it'd be just adding a new TFM to this project and a bunch of code fixes here and there.

Not currently motivated for it though.

**Comment by DestroyerDarkNess** [comment]
Ok thanks, one question, do you have Discord?

**Comment by Sewer56** [comment]
Yeah, it's part of the reason I tend to respond fast.  
I use webhooks to redirect my notifications to Discord.  

Just that I'm currently not interested on working on this.
