### ISSUE TITLE
Reloaded.Hooks.Definitions Source?

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Sewer56/Reloaded.Imgui.Hook#5]
is your "Reloaded.Hooks.Definitions" library closed source? I want to review the code of your CreateHook function, I need alternatives to EasyHook and minhook.net for my renderspy project.

**Comment by Sewer56** [comment]
It's here https://github.com/Reloaded-Project/Reloaded.Hooks/tree/master/source/Reloaded.Hooks.Definitions

**Comment by DestroyerDarkNess** [comment]
Wow, that response was quick. Thanks, I'm going to inspiration from your code XD

**Comment by Sewer56** [comment]
I have webhooks set up to ping me on Discord hahaha, so for some repos I find out fairly quickly.
